modLoader = "javafml"
loaderVersion = "[2,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "titlebarchanger"
version = "${version}"
displayName = "TitlebarChanger"
authors = "Talor1n"
description = '''
TitlebarChanger is a client-side mod that allows you to customize the look of the Minecraft window.
Features include titlebar text, colors, and border customization.

⚡ On Windows 11: full functionality (custom colors, rounded corners, border styling).
⚡ On Windows 10: limited support — only Light/Dark theme switching is available.
'''
logoFile = "logo.png"

[[dependencies.titlebarchanger]]
modId = "neoforge"
type = "required"
versionRange = "[21-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.titlebarchanger]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.titlebarchanger]]
modId = "cloth_config"
type = "optional"
versionRange = "[15.0.140,)"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "titlebarchanger.mixins.json"
